version: "3.8"
services:
  infrastructure:
    image: ${CI_REGISTRY_IMAGE:-registry.sys.example.com/devops-ci}:${CI_TAG:-local}
    build: .
    environment:
      PUBLIC_REGISTRY_USERNAME: ${PUBLIC_REGISTRY_USERNAME:-test}
      PUBLIC_REGISTRY_PASSWORD: ${PUBLIC_REGISTRY_PASSWORD:-test}
      TRAEFIK_DOMAIN: ${TRAEFIK_DOMAIN:-traefik.sys.example.com}
      TRAEFIK_USERNAME: ${TRAEFIK_USERNAME:-admin}
      TRAEFIK_PASSWORD: ${TRAEFIK_PASSWORD:-admin}
      PORTAINER_DOMAIN: ${PORTAINER_DOMAIN:-portainer.sys.example.com}
      CERT_EMAIL: ${CERT_EMAIL:-3193631@gmail.com}
      MONITORING_DOMAIN: ${MONITORING_DOMAIN:-sys.example.com}
      MONITORING_USERNAME: ${MONITORING_USERNAME:-admin}
      MONITORING_PASSWORD: ${MONITORING_PASSWORD:-admin}
      REGISTRY_DOMAIN: ${REGISTRY_DOMAIN:-registry.sys.example.com}
      REGISTRY_USER: ${REGISTRY_USER:-admin}
      REGISTRY_PASSWORD: ${REGISTRY_PASSWORD:-admin}
      GITEA_DOMAIN: ${GITEA_DOMAIN:-gitea.example.com}
      # SKIP CONFIG SECTIONS
      # SKIP_TRAEFIK: "yes"
      # SKIP_MONITORING: "yes"
      # SKIP_PORTAINER: "yes"
      # SKIP_REGISTRY: "yes"
      SKIP_GITEA: "yes"
      # SKIP_UNISON: "yes"
      # SKIP_SLEEP: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # restart: on-failure
    deploy:
      restart_policy:
        condition: none
